services:
  mysql:
    image: mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: po_mysql
    env_file: .env
    volumes:
      - po_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 5

  django:
    image: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: po_django
    env_file: .env
    volumes:
      - ./backend:/po_django
    ports:
      - "8020:8000"
    depends_on:
      mysql:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
volumes:
  po_data:
    name: po_data