services:
  mysql:
    image: mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: po_mysql
    env_file: .env
    volumes:
      - po_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - po_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  django:
    image: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: po_django
    env_file: .env
    volumes:
      - ./backend:/po_django
    ports:
      - "8020:8000"
    networks:
      - po_network
    depends_on:
      mysql:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

  node:
    image: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: po_node
    env_file: .env
    volumes:
      - ./frontend:/po_node
      - /po_node/node_modules
    ports:
      - "8080:8080"
    networks:
      - po_network
    depends_on:
      - django
    command: npm run serve

  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: po_papercut
    ports:
      - "8090:80"
      - "25:25"
    networks:
      - po_network

volumes:
  po_data:
    name: po_data

networks:
  po_network: