# Generated by Django 5.1.3 on 2024-11-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0003_activities_allergens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='allergens',
            options={'verbose_name_plural': 'Allergens'},
        ),
    ]
