from django.contrib.auth.models import AbstractUser
from django.db import models


class Users(AbstractUser):
    """
    Using the AbstractUser model from Django, which has provided fields:
        - id : Primary key, automatically generated by Django.
        - username : Username of the user.
        - email : email address with validation type by django.
        - password : password automatically hashed.
        - first_name et last_name.
        - is_staff : Set the staff status, so can access the admin site.
        - is_superuser : Set the superuser status, so can access the admin site and manage everything.
        - is_active : Specify if user is active or not.
        - last_login : Last login date.
        - date_joined : Creation date.

    Ovveride the default Django User model to add unique option to email field.
    Adding address field to the user model.
    """

    email = models.EmailField(unique=True, blank=False, null=False)
    address = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        """
        Returns a string representation of the user object.
        """
        return f"{self.username} ({self.email})"


class Activities(models.Model):
    """
    Model representing an activity.
    """
    name = models.CharField(
        unique=True, max_length=100, blank=False, null=False)
    description = models.CharField(
        unique=True, max_length=255, blank=False, null=False)

    def __str__(self):
        """
        Returns a string representation of the activity object.
        """
        return f"{self.name} ({self.description})"

    class Meta:
        verbose_name_plural = "Activities"


class Allergens(models.Model):
    """
    Model representing an allergen.
    """
    name = models.CharField(
        unique=True, max_length=100, blank=False, null=False)
    description = models.CharField(
        unique=True, max_length=255, blank=False, null=False)

    def __str__(self):
        """
        Returns a string representation of the allergen object.
        """
        return f"{self.name} ({self.description})"

    class Meta:
        verbose_name_plural = "Allergens"


class UserActivities(models.Model):
    """
    Model representing a user's activity.
    """
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    activity_id = models.ForeignKey(Activities, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("user_id", "activity_id")
        verbose_name_plural = "UserActivities"

    def __str__(self) -> str:
        """
        Returns a string representation of the user activity object.
        """
        return f"{self.user_id.username} {self.activity_id.name}"


class UserAllergens(models.Model):
    """
    Model representing a user's allergen.
    """
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    allergen_id = models.ForeignKey(Allergens, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("user_id", "allergen_id")
        verbose_name_plural = "UserAllergens"

    def __str__(self) -> str:
        """
        Returns a string representation of the user allergen object.
        """
        return f"{self.user_id.username} - {self.allergen_id.name}"


class PlannedActivities(models.Model):
    """
    Model representing a planned activity by a user.
    """
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    activity_id = models.ForeignKey(Activities, on_delete=models.CASCADE)
    location = models.CharField(max_length=250)
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        unique_together = ("user_id", "activity_id", "start_date", "end_date")
        verbose_name_plural = "PlannedActivities"

    def __str__(self) -> str:
        """
        Returns a string representation of the planned activity object.
        """
        return f"{self.user_id.username} {self.activity_id.name} {self.start_date} {self.end_date}"
