from rest_framework import serializers
from .models import Users, Activities, Allergens, UserActivities, UserAllergens, PlannedActivities


class UsersSerializer(serializers.ModelSerializer):
    """
    Serializer for the Users model:
    - id : Primary key, automatically generated by Django.
    - username : Username of the user.
    - password : password automatically hashed.
    - email : email address with validation type by django.
    - address : Address of the user.
    """
    class Meta:
        model = Users
        fields = ['id', 'username', 'password', 'email', 'address']
        # extra_kwargs = {'password': {'write_only': True}}
    """
    def create(self, validated_data):
        user = Users.objects.create_user(
            username=validated_data['username'],
            password=validated_data['password'],
            email=validated_data['email'],
            address=validated_data['address']
        )
        return user
    """


class ActivitiesSerializer(serializers.ModelSerializer):
    """
    Serializer for the Activities model:
    - id : Primary key, automatically generated by Django.
    - name : Name of the activity.
    - description : Description of the activity.
    """
    class Meta:
        model = Activities
        fields = ['id', 'name', 'description']


class AllergensSerializer(serializers.ModelSerializer):
    """
    Serializer for the Allergens model:
    - id : Primary key, automatically generated by Django.
    - name : Name of the allergen.
    - description : Description of the allergen.
    """
    class Meta:
        model = Allergens
        fields = ['id', 'name', 'description']


class UserActivitiesSerializer(serializers.ModelSerializer):
    """
    Serializer for the UserActivities model:
    - id : Primary key, automatically generated by Django.
    - user_id : User's id.
    - activity_id : Activity's id.
    """
    class Meta:
        model = UserActivities
        fields = ['id', 'user_id', 'activity_id']


class UserAllergensSerializer(serializers.ModelSerializer):
    """
    Serializer for the UserAllergens model:
    - id : Primary key, automatically generated by Django.
    - user_id : User's id.
    - allergen_id : Allergen's id.
    """
    class Meta:
        model = UserAllergens
        fields = ['id', 'user_id', 'allergen_id']


class PlannedActivitiesSerializer(serializers.ModelSerializer):
    """
    Serializer for the PlannedActivities model:
    - id : Primary key, automatically generated by Django.
    - user_id : User's id.
    - activity_id : Activity's id.
    - location : Location of the activity.
    - start_date : Start date of the activity.
    - end_date : End date of the activity.
    """
    class Meta:
        model = PlannedActivities
        fields = ['id', 'user_id', 'activity_id',
                  'location', 'start_date', 'end_date']
